id: A17C1D2BB
title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage and
  Making Offerings to the Buddha together with his retinue of Arhats'
type: translation
pechas:
- I46687674
- I2E2229E8
- IBC52B81B
- I4CA9FEAC
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:27.508058
  last_modified_at: 2023-01-04 12:37:27.508070
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I46687674/3CE8: 19C9
  I2E2229E8/33C7: 19C9
  IBC52B81B/8FB2: 19C9
  I4CA9FEAC/1252: 19C9
